
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.67"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.bech32]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.bellman]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.bip0039]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.blake2b_simd]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.blake2s_simd]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.bls12_381]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.bs58]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.cbc]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.clearscreen]]
version = "1.0.9"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.cxx]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.cxxbridge-flags]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.cxxbridge-macro]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.ed25519-zebra]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.fixed-hash]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.fpe]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.gumdrop]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.gumdrop_derive]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.3"
criteria = "safe-to-deploy"

[[exemptions.hdwallet]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.25"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.60"
criteria = "safe-to-deploy"

[[exemptions.jubjub]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.151"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.0.1"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.6.3"
criteria = "safe-to-deploy"

[[exemptions.memuse]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.metrics]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-prometheus]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.metrics-macros]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.metrics-util]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.nonempty]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.30.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.pairing]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.password-hash]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.pasta_curves]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.phf]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_codegen]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_generator]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_shared]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.poly1305]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.primitive-types]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.quanta]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.raw-cpuid]]
version = "10.6.0"
criteria = "safe-to-deploy"

[[exemptions.reddsa]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.9.5"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.27"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.ripemd]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.28"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.secp256k1]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.secp256k1-sys]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.81"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.sketches-ddsketch]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.102"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.terminfo]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.35.0"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-appender]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.uint]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.89"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.66"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.xdg]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.31"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.31"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.3.2"
criteria = "safe-to-deploy"
